name: Regression Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1"

jobs:
  regression-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Install dependencies
        run: npm ci

      - name: Run Regression Tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --env grep=@regression
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME}}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD}}

      - name: Upload Regression Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Regression Report
          path: cypress/reports/html/Regression_index.html
          if-no-files-found: ignore

      - name: Deploy Regression Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: cypress/reports/html
          destination_dir: regression

      - name: Add Regression Link to Summary
        if: always()
        run: |
          echo "### ðŸ“Š Regression Report" >> $GITHUB_STEP_SUMMARY
          echo "[View Regression Report](https://volkantutunculer.github.io/pedogist.com_test/regression/index.html)" >> $GITHUB_STEP_SUMMARY